obj-$(CONFIG_MACH_PROTOU) += board-protou-panel.o
obj-$(CONFIG_MACH_PROTODUG) += board-protou-panel.o
obj-$(CONFIG_MACH_PROTODCG) += board-protodcg-panel.o
obj-$(CONFIG_MACH_MAGNIDS) += board-magnids-panel.o
obj-$(CONFIG_MACH_Z4U) +=  board-z4-panel.o
